version: '3'

services:
  rosbridge:
    command: bash -c "cd src/murosa_plan_health/launch && ros2 launch rosbridge_server rosbridge_websocket_launch.xml"
    image: health_ros
    # network_mode: host
    ports:
      - "9090:9090"
    expose:
      - "9090"
  jason:
    command: bash -c 'cd jason_health && ./gradlew run'
    image: health_ros
    network_mode: host
  health:
    command: bash -c "cd src/murosa_plan_health/launch && ros2 launch murosa_plan_health planning.launch.py"
    image: health_ros
    # network_mode: host
    environment:
      - REPLAN=True
      - PROBLEM_RATE=100
  topic:
    command: bash -c "cd src/murosa_plan_health/launch && ros2 topic echo /coordinator/jason/plan"
    image: health_ros
  info:
    command: bash -c "cd src/murosa_plan_health/launch && ros2 topic info /move_base/move"
    image: health_ros
  sub:
    command: bash -c 'cd src/murosa_plan_health/launch && ros2 topic pub /move_base/move std_msgs/String'
    image: health_ros
  run:
    image: health_ros
    environment:
      - REPLAN=False
      - PROBLEM_RATE=10