gnome-terminal -- bash -c "./scripts/rosbridge.sh; exec bash"
# gnome-terminal -- bash -c "./scripts/jason.sh; exec bash"
gnome-terminal -- bash -c "./scripts/coordinator.sh; exec bash"
gnome-terminal -- bash -c "./scripts/agents.sh; exec bash"
gnome-terminal -- bash -c "./scripts/front.sh; exec bash"